### ISSUE TITLE
Size parameter?

### ISSUE THREAD

**Issue by timathom** [yale-datachemist/entity-resolution#43]
In the VectorLink commands, how is the value of the size parameter chosen? For example, why 8738134 here?

```
vectorlink load -k $OPENAI_KEY -c fakecommit --domain loc -d vector_storage -i authority_ops.json --size 8738134 --build-index true -m small3
```

**Comment by matko** [comment]
The size parameter used to express how large the buffer pool was. Since then though, we switched away from the buffer pool approach and just load everything in memory as is. It's still there to not break old instructions, but it actually doesn't do anything and can be left out of commands.
I updated the readme to omit the size parameters.
